// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/main.go
package handler

func (s *Handler) Reset() {
	if s == nil {
		return
	}

	if s.key != nil {
		s.key = (s.key)[:0]
	}

}
