// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/main.go
package repository

func (s *DBStorage) Reset() {
	if s == nil {
		return
	}

	s.db = nil

	s.logger = nil

}

func (s *MemStorage) Reset() {
	if s == nil {
		return
	}

	clear(s.gauges)

	clear(s.counters)

}
