// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/main.go
package service

func (s *Service) Reset() {
	if s == nil {
		return
	}

	s.logger = nil

	if s.observers != nil {
		s.observers = (s.observers)[:0]
	}

}
